In [1]:
import numpy as np
import pandas as pd

In [2]:
a = np.array([[1,2,3,4],[2,4,6,8],[3,6,9,12],[4,8,12,16]])
a

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

In [3]:
b = np.array([1,2,3,4])

In [4]:
c = b - b.mean()
c

array([-1.5, -0.5,  0.5,  1.5])

In [5]:
aa = a-np.mean(a)
np.matmul(aa,aa.T)

array([[ 61.25,  28.75,  -3.75, -36.25],
       [ 28.75,  26.25,  23.75,  21.25],
       [ -3.75,  23.75,  51.25,  78.75],
       [-36.25,  21.25,  78.75, 136.25]])

In [6]:
np.dot(aa,aa.T)

array([[ 61.25,  28.75,  -3.75, -36.25],
       [ 28.75,  26.25,  23.75,  21.25],
       [ -3.75,  23.75,  51.25,  78.75],
       [-36.25,  21.25,  78.75, 136.25]])

In [7]:
aa.dot(aa)

array([[ 61.25,  28.75,  -3.75, -36.25],
       [ 28.75,  26.25,  23.75,  21.25],
       [ -3.75,  23.75,  51.25,  78.75],
       [-36.25,  21.25,  78.75, 136.25]])

In [8]:
np.cov(a)

array([[ 1.66666667,  3.33333333,  5.        ,  6.66666667],
       [ 3.33333333,  6.66666667, 10.        , 13.33333333],
       [ 5.        , 10.        , 15.        , 20.        ],
       [ 6.66666667, 13.33333333, 20.        , 26.66666667]])

In [9]:
b = pd.DataFrame(np.array([[2.1,8],[2.5,10],[3.6,12],[4,14]]), columns=['num1','num2'])
b.cov()


num1      num2
num1  0.803333  2.266667
num2  2.266667  6.666667

In [10]:
bb = np.array([[2.1,8],[2.5,10],[3.6,12],[4,14]])
np.cov(bb)


array([[17.405, 22.125, 24.78 , 29.5  ],
       [22.125, 28.125, 31.5  , 37.5  ],
       [24.78 , 31.5  , 35.28 , 42.   ],
       [29.5  , 37.5  , 42.   , 50.   ]])

In [12]:
cc = np.array([[90,90,60,60,30],[60,90,60,60,30],[90,30,60,90,30]])
cc

array([[90, 90, 60, 60, 30],
       [60, 90, 60, 60, 30],
       [90, 30, 60, 90, 30]])

In [13]:
np.cov(cc)

array([[630., 450., 225.],
       [450., 450.,   0.],
       [225.,   0., 900.]])